name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

env:
  HUSKY: 0

jobs:
  build:
    name: Main
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: yarn build --ignore="apps/**/*"

  lint:
    name: Main
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn install
      - name: Lint
        run: yarn lint
